server {
    listen 80;
    listen [::]:80;
    server_name injoo.duckdns.org;

    root /usr/share/nginx/html;
    index index.html;

    # --- Основной роутинг SPA ---
    location / {
        try_files $uri $uri/ /index.html;
    }

    # --- Статические файлы ---
    location ~* \.(?:js|css|png|jpg|jpeg|gif|ico|woff2?|ttf|eot|svg|map)$ {
        expires 30d;
        add_header Cache-Control "public, no-transform";
        try_files $uri =404;
    }

    # --- Ошибки ---
    error_page 404 /index.html;
}
