server {
    listen 80;
    listen [::]:80;
    server_name injoo.duckdns.org; # Укажите ваш домен

    # Указываем корневую директорию, где находятся статические файлы
    root /usr/share/nginx/html;
    index index.html index.htm;

    # Основная логика для SPA
    location / {
        try_files $uri $uri/ /index.html;
    }

    location ~* \.(js|css|png|jpg|jpeg|gif|ico|woff|woff2|ttf|eot|svg)$ {
         expires 30d;
         add_header Cache-Control "public, no-transform";
         try_files $uri =404;
    }

}