server {
  listen 80;
  server_name _;

  client_max_body_size 20M;

  root /usr/share/nginx/html;
  index index.html;

  location / {
    try_files $uri $uri/ /index.html;
  }

  # (Необязательно) оптимизация кеша для статики
  location ~* \.(?:ico|css|js|gif|jpe?g|png|woff2?|eot|ttf|svg)$ {
    expires 1y;
    add_header Cache-Control "public";
  }
}
