server {
  listen 80;
  server_name injoo.kz;

  root /usr/share/nginx/html;
  index index.html;

  location / {
    try_files $uri $uri/ /index.html;
    client_max_body_size 100M;
  }
  location = /sitemap.xml {
    proxy_pass https://server.injoo.kz/sitemap.xml;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
}
  # (Необязательно) оптимизация кеша для статики
  location ~* \.(?:ico|css|js|gif|jpe?g|png|woff2?|eot|ttf|svg)$ {
    expires 1y;
    add_header Cache-Control "public";
  }
}
