# Редирект с HTTP на HTTPS
server {
    listen 80;
    server_name injoo.kz www.injoo.kz;
    return 301 https://injoo.kz$request_uri;
}

# Основной блок HTTPS с поддержкой HTTP/2
server {
    listen 443 ssl http2; # Включаем HTTP/2 здесь
    server_name injoo.kz;

    root /usr/share/nginx/html;
    index index.html;

    # --- Глобальный Gzip (сжимает всё, включая динамику) ---
    gzip on;
    gzip_vary on;
    gzip_proxied any;
    gzip_comp_level 6;
    gzip_min_length 256;
    gzip_types
        text/plain
        text/css
        text/javascript
        text/xml
        application/javascript
        application/x-javascript
        application/json
        application/xml
        application/xml+rss
        image/svg+xml;

    # --- Настройка путей SPA ---
    location / {
        try_files $uri $uri/ /index.html;
        client_max_body_size 100M;

        # Добавляем подсказку браузеру загрузить API раньше, чем исполнится JS
        add_header Link "</menu/>; rel=preload; as=fetch; crossorigin" always;
    }

    # --- Кэширование статики (JS, CSS, Картинки) ---
    location ~* \.(?:ico|css|js|gif|jpe?g|png|woff2?|eot|ttf|svg|webp|avif)$ {
        expires 1y;
        add_header Cache-Control "public, no-transform";
        access_log off;
        log_not_found off;
    }

    # --- Прокси для Sitemap или API ---
    location = /sitemap.xml {
        proxy_pass https://server.injoo.kz/sitemap.xml;
        proxy_set_header Host server.injoo.kz;
        proxy_set_header X-Real-IP $remote_addr;
    }
}