services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    labels:
      com.github.nginx-proxy.nginx: "true"
    environment:
      TRUST_DOWNSTREAM_PROXY: "false"
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend/html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs
      - ./vhost:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
    networks:
      - injoo_net

  letsencrypt:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-le
    depends_on:
      - nginx-proxy
    environment:
      NGINX_PROXY_CONTAINER: nginx-proxy
      DEFAULT_EMAIL: injoo.kaskelen@gmail.com
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./certs:/etc/nginx/certs
      - ./vhost:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
      - ./acme:/etc/acme.sh
    networks:
      - injoo_net

  db:
    image: postgres:15
    container_name: injoo-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-injoo_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-injoo_pass}
      POSTGRES_DB: ${POSTGRES_DB:-injoo_db}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - injoo_net

  injoo-app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: injoo-app
    restart: always
    env_file:
      - .env
    expose:
      - "10000"
    environment:
      - VIRTUAL_HOST=server.injoo.kz
      - VIRTUAL_PORT=10000
      - LETSENCRYPT_HOST=server.injoo.kz
      - LETSENCRYPT_EMAIL=injoo.kaskelen@gmail.com
    volumes:
      - ./uploaded_images:/app/uploaded_images
    depends_on:
      - db
    networks:
      - injoo_net

  injoo-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file:
      - ./frontend/.env
    container_name: injoo-frontend
    restart: always
    expose:
      - "80"
    environment:
      - VIRTUAL_HOST=injoo.kz
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=injoo.kz
      - LETSENCRYPT_EMAIL=injoo.kaskelen@gmail.com
    depends_on:
      - injoo-app
    networks:
      - injoo_net

volumes:
  postgres_data:
  certs:
  vhost:
  html:
  acme:

networks:
  injoo_net:
    driver: bridge
