# HTTP -> HTTPS редирект
server {
    listen 80;
    server_name injoo.duckdns.org;

    location /.well-known/acme-challenge/ {
        root /usr/share/nginx/html;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

# HTTPS
server {
    listen 443 ssl;
    server_name injoo.duckdns.org;

    # Пути к сертификатам от Let's Encrypt
    ssl_certificate /etc/letsencrypt/live/injoo.duckdns.org/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/injoo.duckdns.org/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    # FRONTEND (Vue билд)
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri /index.html;
    }

    # BACKEND API
    location /api/ {
        proxy_pass http://injoo-app:10000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Swagger UI
    location /docs {
        proxy_pass http://injoo-app:10000/docs;
        proxy_set_header Host $host;
    }

    location /openapi.json {
        proxy_pass http://injoo-app:10000/openapi.json;
        proxy_set_header Host $host;
    }
}
